[tool.poetry]
name = "aimarketanalysis-cli"
version = "1.1.7"
description = "Investment Research for Everyone, Anywhere."
authors = ["AIMarketAnalysis <hello@aimarketanalysis.co>"]
packages = [{ include = "aimarketanalysis_cli" }]
license = "AGPL-3.0-only"
readme = "README.md"
homepage = "https://aimarketanalysis.co"
repository = "https://github.com/naimkatiman/AIMarketAnalysis"
documentation = "https://docs.aimarketanalysis.co/cli"

[tool.poetry.scripts]
aimarketanalysis = 'aimarketanalysis_cli.cli:main'

[tool.poetry.dependencies]
python = "^3.9,<3.13"

# AIMarketAnalysis dependencies
aimarketanalysis = { version = "^4.4.1", extras = ["all"] }

# CLI dependencies
prompt-toolkit = "^3.0.50"
rich = "^13.9.4"
python-dotenv = "^1.0.1"
openpyxl = "^3.1.5"
pywry = "^0.6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
